spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poc_openid
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver

# Specify the DBMS
  jpa:
    database: MYSQL
    show-sql: true
    hibernate.ddl-auto: update
    hibernate.dialect:  org.hibernate.dialect.MySQL5Dialect
    hibernate.naming_strategy:  org.hibernate.cfg.ImprovedNamingStrategy
    properties.jadira.usertype.autoRegisterUserTypes:  true


logging:
  level:
    org:
      hibernate:
        type: TRACE




