spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poc_openid
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver


security:
  oauth2:
    client:
      clientId: to  be updated
      clientSecret: to be updated
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope:  profile,email
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

